export const businessTypes = [
  "Accelerators",
  "Adhesives & Paints",
  "Aerospace",
  "Agriculture",
  "Agriculture and Agribusiness",
  "Architecture & Design",
  "Artificial Intelligence",
  "Arts and Culture",
  "Associations and Federations",
  "Automotive",
  "Automotive Glass",
  "Aviation",
  "Banks and Other Financial Institutions",
  "Beveled Glass",
  "Building Materials",
  "Business Council",
  "Chambers of Commerce and Industry",
  "Chemical Industry",
  "Coloured and Pure Glass",
  "Commerce",
  "Conglomerate",
  "Construction and Engineering",
  "Consultancy",
  "Consumer Goods",
  "Contracting",
  "Corporate",
  "Cosmetics",
  "Decor Glass",
  "Defense/Military",
  "Digital Solution",
  "Diplomatic Mission",
  "Dust Control & Vacuum Cleaners",
  "Economic Development",
  "Education",
  "Energy and Mining",
  "Event Organizer",
  "Facades and Cabins",
  "Facilities Management",
  "Fiber Glass",
  "Fishery",
  "Flat Glass",
  "Flooring",
  "Food & Beverages",
  "Foreign Affairs",
  "Furniture Manufacturers",
  "Glass Machinery",
  "Glass Manufacturing",
  "Government",
  "Government Department",
  "Government Programs and Initiatives",
  "Green Technology and Climate Change",
  "Hand Craft",
  "Handrail",
  "Healthcare and Pharmaceutical",
  "Heat Treated Glass",
  "Hospitality",
  "Immigration Service",
  "Incubators",
  "Infrastructure",
  "Insurance",
  "Inter-governmental organizations (IGOs)",
  "Investment & Trade",
  "Investment and Freezones",
  "Investment Firm",
  "Investment Promotion Agency",
  "Investor",
  "IT/ ICT and Telecommunication",
  "Law and Legal Affairs",
  "Life Sciences",
  "Lightning",
  "Local Government Units",
  "Logistics and Transportation",
  "Luxury Goods & Jewelry",
  "Management & Investment",
  "Manufacturing",
  "Maritime",
  "Marketing",
  "Marketing and Advertising",
  "MDF/ Panels and Laminates",
  "Media",
  "Ministries",
  "Non-Profit Organizations",
  "Oil and Gas",
  "Others",
  "Paper Industry",
  "Partitions Skylights",
  "Pharmaceutical Glass",
  "Plastics",
  "Plywood/ Hardboard Decorative",
  "Private Equity",
  "Private Sector",
  "Professional Services",
  "Property Development",
  "Property Portal",
  "Property Valuation",
  "Protective Glass",
  "Publishing House",
  "Pyrex Glass",
  "Raw Materials",
  "Real Estate",
  "Real Estate Brokers",
  "Regional Organizations",
  "Retail",
  "Robotics",
  "Securit",
  "Shipbuilding",
  "Shock Resistant Glass",
  "Smart Solutions",
  "Software",
  "Sovereign Wealth Funds",
  "Special Economic Zones",
  "Spider Glass",
  "Sports and Recreation",
  "Startups",
  "Supermarket",
  "Supplier",
  "Table Wear",
  "Technology",
  "Textile and Apparel",
  "Timber/ Hardwood & Softwood",
  "Tools & Cutting Machines",
  "Tourism and Hospitality",
  "Trade & Industry",
  "Transportation",
  "Treatment Products and Composite",
  "UN Specialized Agency",
  "Universities & Academic Institutions",
  "Utilities",
  "Veneer",
  "Venture Capital",
  "Venture Capital - PropTech",
  "Water Recycle",
  "Wood",
  "Wood Accessories (Doors-Windows-Fittings)",
  "Wood Furniture Manufacturers",
  "Wood Suppliers",
  "Wood Working Machinery",
  "Wooden Windows and Doors"
];
